In [139]:
import pandas as pd
import numpy as np
from sklearn import metrics



In [140]:
def load_data():
    accidents_2015 = pd.read_csv("datasets/2015-data/Accidents_2015.csv", index_col="Accident_Index")
    accidents_2016 = pd.read_csv("datasets/Accidents_2016.csv", index_col="Accident_Index")
    accidents_all = [accidents_2015, accidents_2016]
    return pd.concat(accidents_all)



In [141]:
#handling missing values
def handle_missing_values(accidents_original):
    accidents_preprocessed = accidents_original.copy()
    accidents_preprocessed.replace(-1, np.NaN, inplace=True)
    print("Missing values per column \n" + str(accidents_preprocessed.isnull().sum()))
    print("\nSize before replace " + str(accidents_preprocessed.shape))
    
    #find column wise modes
    modes = accidents_preprocessed.mode().to_dict(orient='records')[0]
    accidents_preprocessed.fillna(modes, inplace=True)
    
    print("\nVerify missing values per column \n" + str(accidents_preprocessed.isnull().sum()))
    print("\nSize after replace " + str(accidents_preprocessed.shape))
    return accidents_preprocessed



In [119]:
round(abs(-7.3898 - (-7)),2)
round(abs(1.7578 - (-7)),2)

base_longitude = acc['Longitude_X'].min()
base_latitide = acc['Latitude_Y'].min()

test_df = pd.DataFrame()

test_df['location'] = acc['Longitude_X'] * acc['Latitude_Y']

test_df['new_X'] = acc['Longitude_X'] - base_longitude
test_df['new_Y'] = acc['Latitude_Y'] - base_latitide
m = test_df['new_X'].max()
print(m)
test_df['new_loc'] = test_df['new_X'] + test_df['new_Y'] * m

test_df.describe()
#test_df.head(10)

In [142]:

def process_location(accidents_df):
    #accidents_df['Longitude_X'] = accidents_df['Longitude'].apply(lambda l: round(abs(l - (-7)), 2)*100)
    #accidents_df['Latitude_Y'] = accidents_df['Latitude'].apply(lambda l: round(abs(l - (49)), 2)*100)
    accidents_df['Longitude_X'] = accidents_df['Longitude'].apply(lambda l: round(abs(l - (-7)), 1)*10)
    accidents_df['Latitude_Y'] = accidents_df['Latitude'].apply(lambda l: round(abs(l - (49)), 1)*10)

    base_longitude = accidents_df['Longitude_X'].min()
    base_latitide = accidents_df['Latitude_Y'].min()
    accidents_df['Longitude_X_N'] = accidents_df['Longitude_X'] - base_longitude
    accidents_df['Latitude_Y_N'] = accidents_df['Latitude_Y'] - base_latitide
    
    multipier = accidents_df['Longitude_X_N'].max()
    accidents_df['Derived_Location'] = accidents_df['Longitude_X_N'] + accidents_df['Latitude_Y_N'] * multipier
    #accidents_df['Derived_Location'] = accidents_df['Longitude_X'] * accidents_df['Latitude_Y']
    #print(accidents_df.describe())
    return accidents_df

# acc = process_location(accidents_original)
# acc.filter(['Longitude', 'Latitude', 'Longitude_X', 'Latitude_Y', 'Derived_Location']).describe()


In [143]:
# catagorize  the time into 3 hour slots
def process_time(accidents_df):
    accidents_df['Time_Slot'] = accidents_df['Time'].apply(lambda t: int(str(t).split(':', 1)[0])//3)
    return accidents_df


#print(int('4:34'.split(':', 1)[0])//3)
# val = df['Time']['2016010000006'].split(':', 1)[0]
# print(int(val) // 3)


# df['Time_Slot'] = df['Time']
# print(df['Time'].describe())
#df = load_data()
#print(df['Time']['2016010000006'].split(':', 1)[0])


In [144]:
def filter_columns(accidents_df):
    return accidents_df.filter(['Accident_Severity', 'Day_of_Week', 'Road_Type', 'Speed_limit',
                                'Junction_Detail', 'Junction_Control', 'Light_Conditions', 
                                'Weather_Conditions', 'Road_Surface_Conditions',
                                'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities',
                                'Special_Conditions_at_Site', 'Carriageway_Hazards',
                                'Derived_Location', 'Time_Slot'],
                                axis=1)


In [145]:
#driver program

accidents_original = load_data()
print("Original columns : \n" + str(list(accidents_original.columns.values)))

accidents_preprocessed = handle_missing_values(accidents_original)

accidents_preprocessed = process_location(accidents_preprocessed)

accidents_preprocessed = process_time(accidents_preprocessed)

accidents_preprocessed = filter_columns(accidents_preprocessed)

print("\n\nPost preprocessing columns : " + str(list(accidents_preprocessed.columns.values)))
print("\n\nDescribe \n" + str(accidents_preprocessed.describe()))


/Users/anilc/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2850: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


/Users/anilc/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2850: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Original columns : 
['Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control', '2nd_Road_Class', '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident', 'LSOA_of_Accident_Location']


Missing values per column 
Location_Easting_OSGR                              34
Location_Northing_OSGR                             34
Longitude                                          34
Latitude                                           34
Police_Force                                        0
Accident_Severity                                   0
Number_of_Vehicles                                  0
Number_of_Casualties                                0
Date                                                0
Day_of_Week                                         0
Time                                               20
Local_Authority_(District)                          0
Local_Authority_(Highway)                           0
1st_Road_Class                                      0
1st_Road_Number                                     0
Road_Type                                           1
Speed_limit                                        37
Junction_Detail                                   107
J


Verify missing values per column 
Location_Easting_OSGR                          0
Location_Northing_OSGR                         0
Longitude                                      0
Latitude                                       0
Police_Force                                   0
Accident_Severity                              0
Number_of_Vehicles                             0
Number_of_Casualties                           0
Date                                           0
Day_of_Week                                    0
Time                                           0
Local_Authority_(District)                     0
Local_Authority_(Highway)                      0
1st_Road_Class                                 0
1st_Road_Number                                0
Road_Type                                      0
Speed_limit                                    0
Junction_Detail                                0
Junction_Control                               0
2nd_Road_Class                    



Post preprocessing columns : ['Accident_Severity', 'Day_of_Week', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control', 'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Derived_Location', 'Time_Slot']


Describe 
       Accident_Severity    Day_of_Week      Road_Type    Speed_limit  \
count      276677.000000  276677.000000  276677.000000  276677.000000   
mean            2.825121       4.105296       5.176393      38.060012   
std             0.410160       1.914275       1.652676      13.971795   
min             1.000000       1.000000       1.000000       0.000000   
25%             3.000000       2.000000       6.000000      30.000000   
50%             3.000000       4.000000       6.000000      30.000000   
75%             3.000000       6.000000       6.000000      40.000000   
max             3.000000       7.0

In [146]:

def transform_categorical_values(accidents_df):
    
    cols_to_transform = ['Day_of_Week', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control',
                         'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions',
                         'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities',
                         'Special_Conditions_at_Site', 'Carriageway_Hazards',
                         'Derived_Location', 'Time_Slot']
    
    return pd.get_dummies(accidents_df, columns = cols_to_transform)


In [147]:
accidents_onehotencoded = transform_categorical_values(accidents_preprocessed)

input = accidents_onehotencoded.drop(['Accident_Severity'], axis=1)
labels = accidents_onehotencoded.filter(['Accident_Severity'], axis=1)

#print(list(input.columns.values))

print(list(labels.columns.values))


['Accident_Severity']


In [140]:

#TBD

# tbd = accidents_original.filter(['Urban_or_Rural_Area'])
# print(tbd['Pedestrian_Crossing-Human_Control'].value_counts())
# tbd = tbd[tbd['Pedestrian_Crossing-Human_Control'] == -1]
# print(tbd.shape)
# 
# #print(tbd.describe())
# 
# ignored = accidents_original.filter(['Location_Easting_OSGR', 'Location_Northing_OSGR', 'Police_Force',
#                                      'Number_of_Vehicles', 'Number_of_Casualties',
#                                      'Local_Authority_(District)', 'Local_Authority_(Highway)', 
#                                      '1st_Road_Class', '1st_Road_Number', '2nd_Road_Class', '2nd_Road_Number',
#                                      'Did_Police_Officer_Attend_Scene_of_Accident', 'LSOA_of_Accident_Location',
#                                      'Date'])


<class 'str'>
2


In [82]:
#redundant 
# print("missing values i.e. -1")
# print(accidents_filtered[accidents_filtered['Road_Type'] == -1].shape) #1
# print(accidents_filtered[accidents_filtered['Junction_Detail'] == -1].shape) #106
# print(accidents_filtered[accidents_filtered['Junction_Control'] == -1].shape) #56623
# print(accidents_filtered[accidents_filtered['Light_Conditions'] == -1].shape) #13
# print(accidents_filtered[accidents_filtered['Weather_Conditions'] == -1].shape) #13
# print(accidents_filtered[accidents_filtered['Road_Surface_Conditions'] == -1].shape) #13
# 
# print("\nvalue counts")
# print(accidents_filtered['Junction_Control'].value_counts())
# print(accidents_filtered['Light_Conditions'].value_counts())
# print(accidents_filtered['Weather_Conditions'].value_counts())
# print(accidents_filtered['Road_Surface_Conditions'].value_counts())


<class 'str'>
2


In [150]:
from sklearn.cross_validation import train_test_split

input_train, input_test, labels_train, labels_test = train_test_split(input, labels, 
                                                                      test_size=0.25)
print("input_train.shape : " + str(input_train.shape))
print("labels_train.shape : " + str(labels_train.shape))
print("input_test.shape : " + str(input_test.shape))
print("labels_test.shape : " + str(labels_test.shape))

input_train.shape : (207507, 3043)
labels_train.shape : (207507, 1)
input_test.shape : (69170, 3043)
labels_test.shape : (69170, 1)


In [101]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(penalty='l2', C=1000, max_iter=1000)

classifier.fit(input_train, labels_train)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [151]:


def print_metrics(classifier, input, labels_actuals):
    labels_predicts = classifier.predict(input)

    print("Accuracy : " + str(metrics.accuracy_score(labels_actuals, labels_predicts)))
    print("Precision : " + str(metrics.precision_score(labels_actuals, labels_predicts, average=None)))
    print("Recall : " + str(metrics.recall_score(labels_actuals, labels_predicts, average=None)))
    print("F1 score : " + str(metrics.f1_score(labels_actuals, labels_predicts, average=None)))
    print("Confusion Matrix : ")
    print(metrics.confusion_matrix(labels_actuals, labels_predicts))

In [105]:
print("Metrics for training data")
print_metrics(classifier, input_train, labels_train)

print("\nMetrics for test data")
print_metrics(classifier, input_test, labels_test)


Metrics for training data


Accuracy : 0.8321805006587615
Precision : [0.75       0.64560711 0.83398176]
Recall : [0.03944485 0.03768366 0.99640065]
F1 score : [0.07494795 0.0712108  0.90798509]
Confusion Matrix : 
[[   54    40  1275]
 [   11   654 16690]
 [    7   319 90246]]

Metrics for test data


Accuracy : 0.8239707227813358
Precision : [0.         0.28629032 0.82953873]
Recall : [0.         0.01624714 0.99182465]
F1 score : [0.         0.03074924 0.90345175]
Confusion Matrix : 
[[    0     6   320]
 [    7    71  4292]
 [   14   171 22444]]


In [106]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(max_depth=100)
dt_classifier.fit(input_train, labels_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=100,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [107]:
print("Metrics for training data")
print_metrics(dt_classifier, input_train, labels_train)

print("\nMetrics for test data")
print_metrics(dt_classifier, input_test, labels_test)

Metrics for training data


Accuracy : 0.8968397745571659
Precision : [0.97016706 0.95825296 0.89182806]
Recall : [0.59386413 0.40074906 0.99647794]
F1 score : [0.73674671 0.5651485  0.94125315]
Confusion Matrix : 
[[  813     0   556]
 [    9  6955 10391]
 [   16   303 90253]]

Metrics for test data


Accuracy : 0.7982799634034766
Precision : [0.02678571 0.19227609 0.82997384]
Recall : [0.00920245 0.05354691 0.95346679]
F1 score : [0.01369863 0.08376589 0.88744473]
Confusion Matrix : 
[[    3    17   306]
 [   22   234  4114]
 [   87   966 21576]]


In [156]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=20,
                                       max_depth=100,
                                       min_samples_split=5,
                                       min_samples_leaf=5)
rf_classifier.fit(input_train, labels_train)

print("Metrics for training data")
print_metrics(rf_classifier, input_train, labels_train)

print("\nMetrics for test data")
print_metrics(rf_classifier, input_test, labels_test)


/Users/anilc/Library/Python/3.6/lib/python/site-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


Metrics for training data


Accuracy : 0.8372006727483892
Precision : [0.         0.         0.83720067]
Recall : [0. 0. 1.]
F1 score : [0.         0.         0.91138729]
Confusion Matrix : 


/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[     0      0   2465]
 [     0      0  31317]
 [     0      0 173725]]

Metrics for test data


Accuracy : 0.8367500361428365
Precision : [0.         0.         0.83675004]
Recall : [0. 0. 1.]
F1 score : [0.         0.         0.91112021]
Confusion Matrix : 
[[    0     0   846]
 [    0     0 10446]
 [    0     0 57878]]


In [129]:
from sklearn.neural_network import MLPClassifier
nn_classifier = MLPClassifier(hidden_layer_sizes=(100,20,10))
nn_classifier.fit(input_train, labels_train)

print("Metrics for training data")
print_metrics(rf_classifier, input_train, labels_train)

print("\nMetrics for test data")
print_metrics(rf_classifier, input_test, labels_test)



/usr/local/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Metrics for training data


Accuracy : 0.9824787732396428
Precision : [0.98964143 0.98811694 0.98140792]
Recall : [0.94233687 0.90472627 0.99796925]
F1 score : [0.96541003 0.94458469 0.9896193 ]
Confusion Matrix : 
[[ 1242    12    64]
 [    6 15716  1649]
 [    7   177 90423]]

Metrics for test data


Accuracy : 0.8145654162854529
Precision : [0.04347826 0.17276423 0.82700485]
Recall : [0.00265252 0.01952228 0.98132247]
F1 score : [0.005      0.03508048 0.89757914]
Confusion Matrix : 
[[    1     3   373]
 [    4    85  4265]
 [   18   404 22172]]
